<a href="https://colab.research.google.com/github/Neethu0207/CodeAlphaNeethu/blob/main/Credit.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Importing libraries & functions

In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.linear_model import LogisticRegression

# Importing dataset

In [3]:
df = pd.read_excel("/content/a_Dataset_CreditScoring.xlsx")

# Data preparation

In [4]:
df.head()

,TARGET,ID,DerogCnt,CollectCnt,BanruptcyInd,InqCnt06,InqTimeLast,InqFinanceCnt24,TLTimeFirst,TLTimeLast,...,TL50UtilCnt,TLBalHCPct,TLSatPct,TLDel3060Cnt24,TLDel90Cnt24,TLDel60CntAll,TLOpenPct,TLBadDerogCnt,TLDel60Cnt24,TLOpen24Pct
0,1,582,3,3,0,4,0.0,5,117,27,...,3.0,0.9179,0.2083,2,3,7,0.2083,4,4,0.0000
1,1,662,15,9,0,3,1.0,3,14,14,...,1.0,0.8000,0.0000,0,0,0,1.0000,12,0,1.0000
2,1,805,0,0,0,1,5.0,1,354,7,...,5.0,0.3552,0.6538,0,1,1,0.7308,1,1,0.5263
3,1,1175,8,5,0,6,1.0,10,16,4,...,3.0,0.9127,0.2500,1,1,1,0.7500,7,1,1.3333
4,1,1373,3,1,0,9,0.0,8,130,52,...,1.0,1.2511,0.0000,0,1,4,0.1429,3,1,0.0000

In [6]:
df.size

90000

In [7]:
df.shape

(3000, 30)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 30 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   TARGET           3000 non-null   int64
 1   ID               3000 non-null   int64
 2   DerogCnt         3000 non-null   int64
 3   CollectCnt       3000 non-null   int64
 4   BanruptcyInd     3000 non-null   int64
 5   InqCnt06         3000 non-null   int64
 6   InqTimeLast      2812 non-null   float64
 7   InqFinanceCnt24  3000 non-null   int64
 8   TLTimeFirst      3000 non-null   int64
 9   TLTimeLast       3000 non-null   int64
 10  TLCnt03          3000 non-null   int64
 11  TLCnt12          3000 non-null   int64
 12  TLCnt24          3000 non-null   int64
 13  TLCnt            2997 non-null   float64
 14  TLSum            2960 non-null   float64
 15  TLMaxSum         2960 non-null   float64
 16  TLSatCnt         2996 non-null   float64
 17  TLDel60Cnt       3000 non-null   int64
 18  TLBadCnt24       3000 non-null   int64
 19  TL75UtilCnt      2901 non-null   float64
 20  TL50UtilCnt      2901 non-null   float64
 21  TLBalHCPct       2959 non-null   float64
 22  TLSatPct         2996 non-null   float64
 23  TLDel3060Cnt24   3000 non-null   int64
 24  TLDel90Cnt24     3000 non-null   int64
 25  TLDel60CntAll    3000 non-null   int64
 26  TLOpenPct        2997 non-null   float64
 27  TLBadDerogCnt    3000 non-null   int64
 28  TLDel60Cnt24     3000 non-null   int64
 29  TLOpen24Pct      2997 non-null   float64
dtypes: float64(11), int64(19)
memory usage: 703.3 KB

In [10]:
df.dtypes

TARGET               int64
ID                   int64
DerogCnt             int64
CollectCnt           int64
BanruptcyInd         int64
InqCnt06             int64
InqTimeLast        float64
InqFinanceCnt24      int64
TLTimeFirst          int64
TLTimeLast           int64
TLCnt03              int64
TLCnt12              int64
TLCnt24              int64
TLCnt              float64
TLSum              float64
TLMaxSum           float64
TLSatCnt           float64
TLDel60Cnt           int64
TLBadCnt24           int64
TL75UtilCnt        float64
TL50UtilCnt        float64
TLBalHCPct         float64
TLSatPct           float64
TLDel3060Cnt24       int64
TLDel90Cnt24         int64
TLDel60CntAll        int64
TLOpenPct          float64
TLBadDerogCnt        int64
TLDel60Cnt24         int64
TLOpen24Pct        float64
dtype: object

In [17]:
df.describe()

,TARGET,DerogCnt,CollectCnt,BanruptcyInd,InqCnt06,InqTimeLast,InqFinanceCnt24,TLTimeFirst,TLTimeLast,TLCnt03,...,TL50UtilCnt,TLBalHCPct,TLSatPct,TLDel3060Cnt24,TLDel90Cnt24,TLDel60CntAll,TLOpenPct,TLBadDerogCnt,TLDel60Cnt24,TLOpen24Pct
count,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,2812.000000,3000.000000,3000.000000,3000.000000,3000.000000,...,2901.000000,2959.000000,2996.000000,3000.000000,3000.000000,3000.000000,2997.000000,3000.000000,3000.000000,2997.000000
mean,0.166667,1.430000,0.857000,0.153333,3.108333,3.108108,3.555000,170.113667,11.873667,0.275000,...,4.077904,0.648178,0.518331,0.726000,0.814667,2.522000,0.496168,1.409000,1.068333,0.564219
std,0.372740,2.731469,2.161352,0.360369,3.479171,4.637831,4.477536,92.813700,16.321412,0.582084,...,3.108076,0.266486,0.234759,1.163633,1.609508,3.407255,0.206722,2.460434,1.806124,0.480105
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,106.000000,4.000000,0.000000,...,2.000000,0.501100,0.352900,0.000000,0.000000,0.000000,0.344800,0.000000,0.000000,0.250000
50%,0.000000,0.000000,0.000000,0.000000,2.000000,1.000000,2.000000,151.000000,7.000000,0.000000,...,3.000000,0.695500,0.527050,0.000000,0.000000,1.000000,0.500000,0.000000,0.000000,0.500000
75%,0.000000,2.000000,1.000000,0.000000,4.000000,3.000000,5.000000,227.000000,13.000000,0.000000,...,6.000000,0.840650,0.681800,2.000000,1.000000,4.000000,0.625000,2.000000,1.000000,0.800000
max,1.000000,51.000000,50.000000,1.000000,40.000000,24.000000,48.000000,933.000000,342.000000,7.000000,...,23.000000,3.361300,1.000000,8.000000,19.000000,45.000000,1.000000,47.000000,20.000000,6.000000

In [18]:
#dropping customer ID column from the dataset
df.shape

(3000, 29)

In [19]:
#checking null values
df.isnull().sum()

TARGET               0
DerogCnt             0
CollectCnt           0
BanruptcyInd         0
InqCnt06             0
InqTimeLast        188
InqFinanceCnt24      0
TLTimeFirst          0
TLTimeLast           0
TLCnt03              0
TLCnt12              0
TLCnt24              0
TLCnt                3
TLSum               40
TLMaxSum            40
TLSatCnt             4
TLDel60Cnt           0
TLBadCnt24           0
TL75UtilCnt         99
TL50UtilCnt         99
TLBalHCPct          41
TLSatPct             4
TLDel3060Cnt24       0
TLDel90Cnt24         0
TLDel60CntAll        0
TLOpenPct            3
TLBadDerogCnt        0
TLDel60Cnt24         0
TLOpen24Pct          3
dtype: int64

In [20]:
# filling missing values with mean
df.fillna(df.mean(), inplace=True)

In [21]:
# explore missing values post missing value fix
print(df.isnull().sum())

TARGET             0
DerogCnt           0
CollectCnt         0
BanruptcyInd       0
InqCnt06           0
InqTimeLast        0
InqFinanceCnt24    0
TLTimeFirst        0
TLTimeLast         0
TLCnt03            0
TLCnt12            0
TLCnt24            0
TLCnt              0
TLSum              0
TLMaxSum           0
TLSatCnt           0
TLDel60Cnt         0
TLBadCnt24         0
TL75UtilCnt        0
TL50UtilCnt        0
TLBalHCPct         0
TLSatPct           0
TLDel3060Cnt24     0
TLDel90Cnt24       0
TLDel60CntAll      0
TLOpenPct          0
TLBadDerogCnt      0
TLDel60Cnt24       0
TLOpen24Pct        0
dtype: int64

# TRAIN TEST

In [22]:
y = df.iloc[:, 0].values
X = df.iloc[:, 1:29].values

In [23]:
# splitting dataset into training and test (in ratio 80:20)

X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                    test_size=0.2,
                                                    random_state=0,
                                                    stratify=y)

# Risk Model building

In [24]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [25]:
classifier =  LogisticRegression()
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)

# Model performance

In [27]:
print(accuracy_score(y_test, y_pred))

0.8333333333333334

In [28]:
#calculate precision
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.85      0.97      0.91       500
           1       0.50      0.13      0.21       100

    accuracy                           0.83       600
   macro avg       0.67      0.55      0.56       600
weighted avg       0.79      0.83      0.79       600

In [26]:
print(confusion_matrix(y_test,y_pred))

[[487  13]
 [ 87  13]]

In [32]:
#calculating roc-auc
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test, y_pred)

np.float64(0.5519999999999999)

# Writing output file

In [29]:
predictions = classifier.predict_proba(X_test)
predictions

array([[0.61598311, 0.38401689],
       [0.98854759, 0.01145241],
       [0.87096661, 0.12903339],
       ...,
       [0.9445091 , 0.0554909 ],
       [0.46946796, 0.53053204],
       [0.94009714, 0.05990286]])

In [31]:
# writing model output file

df_prediction_prob = pd.DataFrame(predictions, columns = ['prob_0', 'prob_1'])
df_prediction_target = pd.DataFrame(classifier.predict(X_test), columns = ['predicted_TARGET'])
df_test_dataset = pd.DataFrame(y_test,columns= ['Actual Outcome'])

dfx=pd.concat([df_test_dataset, df_prediction_prob, df_prediction_target], axis=1)

dfx.to_csv("/content/a_Dataset_CreditScoring.xlsx", sep=',', encoding='UTF-8')

dfx.head()

   Actual Outcome    prob_0    prob_1  predicted_TARGET
0               1  0.615983  0.384017                 0
1               0  0.988548  0.011452                 0
2               1  0.870967  0.129033                 0
3               0  0.954084  0.045916                 0
4               1  0.726195  0.273805                 0